# Generated by Django 5.1.4 on 2024-12-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nutritionist',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nutritionist',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='nutritionist',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nutritionist',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='nutritionist',
            name='registration_number',
            field=models.CharField(max_length=20),
        ),
    ]
