# Generated by Django 5.1.4 on 2024-12-27 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_nutritionist_is_active_nutritionist_is_staff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='nutritionist',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='nutritionist',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='nutritionist',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='nutritionist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='nutritionist',
            name='password',
        ),
        migrations.AddField(
            model_name='nutritionist',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
