# Generated by Django 5.1.4 on 2024-12-29 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_nutritionist_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nutritionist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.nutritionist'),
        ),
    ]
